import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/shared/NavBar";
import Footer from "@/components/shared/Footer";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={` h-screen flex flex-col`}>
        <header>
          <NavBar />
        </header>
        <main className="flex-1">{children}</main>
        <footer>
          <Footer />
        </footer>
      </body>
    </html>
  );
}
